### ISSUE TITLE
Chapter3 - Phab2 Pro specs

### ISSUE THREAD

**Issue by hustcy** [sjfricke/Tango-C-NDK-Tutorial#1]
"The Tegra chip is way less powerful then the Snapdragon 810 the Phab 2 Pro is running"

-- The model of Snapdragon of Phab2 Pro is 652.

**Comment by sjfricke** [comment]
You are correct, I don't know why I had 810 in my mind... also the ZenPhone has a 821 coming with it

Thnaks for the catch!!!
